# =============================================================================
# 05-rabbitmq.yaml  (namespace grupo4-qa)  —  Message Broker
# Deployment (rabbitmq:3-management-alpine) + Service ClusterIP (amqp+panel).
# PROD: cambiar namespace -> grupo4-prod.
# -----------------------------------------------------------------------------
# Verificar:
#   kubectl get pods,svc -n grupo4-qa -l app=rabbitmq
#   kubectl exec -n grupo4-qa deploy/rabbitmq -- rabbitmq-diagnostics -q ping
#   kubectl port-forward -n grupo4-qa svc/rabbitmq 15672:15672   # -> http://localhost:15672
# =============================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: grupo4-qa
  labels:
    app: rabbitmq
    app.kubernetes.io/part-of: smartgrid
    app.kubernetes.io/managed-by: grupo4
    entorno: qa
spec:
  replicas: 1
  selector:
    matchLabels: { app: rabbitmq }
  template:
    metadata:
      labels:
        app: rabbitmq
        app.kubernetes.io/part-of: smartgrid
        entorno: qa
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management-alpine
          ports:
            - { name: amqp, containerPort: 5672 }
            - { name: management, containerPort: 15672 }
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom: { secretKeyRef: { name: smartgrid-secrets, key: RABBITMQ_DEFAULT_USER } }
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom: { secretKeyRef: { name: smartgrid-secrets, key: RABBITMQ_DEFAULT_PASS } }
          readinessProbe:
            exec: { command: ["rabbitmq-diagnostics","-q","ping"] }
            initialDelaySeconds: 15
            periodSeconds: 15
          livenessProbe:
            exec: { command: ["rabbitmq-diagnostics","-q","ping"] }
            initialDelaySeconds: 40
            periodSeconds: 30
          resources:
            requests: { cpu: 100m, memory: 256Mi }
            limits:   { cpu: 500m, memory: 512Mi }
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: grupo4-qa
  labels: { app: rabbitmq, app.kubernetes.io/part-of: smartgrid, entorno: qa }
spec:
  type: ClusterIP
  selector: { app: rabbitmq }
  ports:
    - { name: amqp, port: 5672, targetPort: 5672 }
    - { name: management, port: 15672, targetPort: 15672 }
